name: main

on:
  push:
    tags: ["v**"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore --nologo

      - name: Build and Test
        run: |
          dotnet build --no-restore --nologo
          dotnet test --no-build --verbosity normal --nologo

      - name: Create NuGet Package
        run: |
          dotnet publish --no-restore --nologo
          dotnet pack --nologo

      - name: Publish NuGet Package
        run: dotnet nuget push **/*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --no-symbols true --skip-duplicate
