name: test source

on:
  push:
    branches: ["main", "develop", "feature/**"]
  pull_request:
    branches: ["main", "develop", "feature/**"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore --nologo

      - name: Build
        run: dotnet build --no-restore --nologo

      - name: Test
        run: dotnet test --no-build --verbosity normal --nologo
